### ISSUE TITLE
Classes Dumper and HtmlDumper not found after composer update

### ISSUE THREAD

**Issue by be-mohand** [tightenco/collect#124]
Hi,

After a composer update, I have those errors in my terminal when I call shell commands:
PHP Warning:  Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /home/kreezalid/app/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18
PHP Warning:  Class 'Tightenco\Collect\Support\Debug\HtmlDumper' not found in /home/kreezalid/app/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18

Here are the composer update info:
Package operations: 0 installs, 2 updates, 0 removals
  - Updating aws/aws-sdk-php (3.67.4 => 3.67.5): Downloading (100%)         
  - Updating tightenco/collect (v5.6.37 => v5.7.1): Downloading (100%)

I'm using CakePHP but I think one of my dependances is using your package.

Cheers

**Comment by mattstauffer** [comment]
@be-mohand have you been able to figure out which dependency it is, by the way? I've fixed it on our end but I won't be able to push out a fix until Laravel 5.7.3 comes out, and there's no way to predict when that's going to be.

**Comment by mattstauffer** [comment]
Thanks! Yah anyone with control of the dependencies can just lock it to under 7.0 until the next Laravel release comes out which will hopefully be soon :)

**Comment by mattstauffer** [comment]
And the good news is that nothing is broken. It’s just annoying, temporarily.

**Comment by jeremyvaught** [comment]
FWIW I'm getting this globally due to Valet

**Comment by mattstauffer** [comment]
Yah, there’s an issue in valet repo saying the same thing. It’ll go away as soon as Laravel pushes a new version and you update valet.

**Comment by Vormillion** [comment]
Hi,

The same thing happens with module kunalvarma05/dropbox-php-sdk 0.2.1 which requires tightenco/collect ^5.2.

**Comment by YouYII** [comment]
This can solve this problem temporarily.
`composer require tightenco/collect:v5.6.27`

**Comment by mattstauffer** [comment]
That’s fine but not necessary; it’s fixed in the latest.

**Comment by monro93** [comment]
Hi @mattstauffer ,
We still have the warning, I have been looking at the cause, is caused because we have symfony 3.4 and in the last tag (5.7.2) the library requires `"symfony/var-dumper": "^4.1"` which is not compatible with the requirements from symfony for the var-dumper (3.4.*), so the composer update resolve to install the version 5.7.1, that still have the issue.
Regards!

**Comment by mattstauffer** [comment]
Ugh that sucks. Can you manually set a constraint to get Collect less than 5.7.0 then?

**Comment by monro93** [comment]
I will try to open a PR, but I don't have too much expectations :(
Thanks

**Comment by mattstauffer** [comment]
Monro I’ll check!

**Comment by samirfor** [comment]
> This can solve this problem temporarily.
> `composer require tightenco/collect:v5.6.27`

Works with "zendframework/zendframework1": "1.12.19"
